# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25e209fd476a34544d242191d2697f6710161ae02c5428d86adddee99217c97df285a5a4edcdadafbc5158180171e9a9f27ce463cf94f704cbea0f9ee16e20ad

test:
  secret_key_base: a25b303cbb5adec84348f02fb570c5f5c2e5872504f24f1481ba9726a0af337adef2eda444f67f945ca8acbb57446e6e6171b048d5ec81e15a8973a6f7a8db29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
